accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)
from django.urls import path

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDetailView,
)

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="delete_task"),
    path("<int:pk>/detail", TaskDetailView.as_view(), name="task_detail"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

accounts/models.py
# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="projects"
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField(null=False, blank=False)
    due_date = models.DateTimeField(auto_now=False, null=False)
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )
    description = models.CharField(max_length=200, null=True, blank=True)
    notes = models.CharField(max_length=400, null=True, blank=True)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from projects.models import Project
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"
    success_url = "home"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self) -> str:
        return reverse_lazy("show_project", args=[self.object.id])

tasks/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task
from django.urls import reverse_lazy

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = [
        "name",
        "start_date",
        "due_date",
        "project",
        "assignee",
        "description",
    ]

    def get_success_url(self) -> str:
        return reverse_lazy("show_project", args=[self.object.project.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = "/tasks/mine/"


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    fields = ["delete"]
    success_url = "/tasks/mine/"


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    fields = ["description"]
    template_name = "tasks/detail.html"

projects/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tracker</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'list_projects' %}">My projects</a>
          </li>
          <li>
            <a href="{% url 'show_my_tasks' %}">My tasks</a>
          </li>
          <li>
            <a href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'login' %}">Login</a>
          </li>
          <li>
            <a href="{% url 'signup' %}">Signup</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    {% block content %}
    <main></main>
    {% endblock content %}
  </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}{% block content %}
<main>
  <div>
    <h1>Create a new project</h1>
    <div class="narrow_form">
      <form method="post" class="narrow-form">
        {% csrf_token %}{{ form.as_p }}
        <button class="create_project">Create</button>
      </form>
    </div>
  </div>
</main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %} {% load markdownify %} {% block content %}
<main>
  <div>
    <h1>{{ project.name }}</h1>
    {{ project.description|markdownify }}
    <h2>Tasks</h2>
    {% if project.tasks.all|length == 0 %}
    <p>This project has no tasks</p>
    {% else %}
    <table class="task_table">
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Assignee</th>
          <th>Start date</th>
          <th>Due date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for task in project.tasks.all %}
        <tr>
          {% if task.is_complete == True %}
          <td>&#10004;</td>
          {% else %}
          <td>
            <form method="post" action="{% url 'complete_task' task.id %}">
              {% csrf_token %}
              <input type="hidden" name="is_completed" value="True" />
              <button class="task_complete">&#10004;</button>
            </form>
          </td>
          <td><a href="{% url 'task_detail' task.id %}">{{ task.name }}</a></td>
          <td>{{ task.assignee }}</td>
          <td>{{ task.start_date }}</td>
          <td>{{ task.due_date }}</td>

          <td>
            <form method="post" action="{% url 'delete_task' task.id %}">
              {% csrf_token %}
              <input type="hidden" name="delete_task" value="True" />
              <button class="task_delete">X</button>
            </form>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
    <div>
      <p>
        <a href="{% url 'create_task' %}">
        <button class="task_create">+ PROJECT</button></a>
      </p>
  </div>
</main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}{% block content %}
<main>
  <div>
    <h1>My Projects</h1>
    {% if project_list|length == 0 %}
    <p>You are not assigned to any projects</p>
    {% else %}
    <table class="project_table">
      <thead class="task_head">
        <tr>
          <th>Name</th>
          <th>Number of tasks</th>
        </tr>
      </thead>
      <tbody>
        {% for project in project_list %}
        <tr>
          <td>
            <a href="{% url 'show_project' project.pk %}">{{ project.name }}</a>
          </td>
          <td>{{ project.tasks.all | length }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <p>
      <a href="{% url 'create_project' %}">
        <button class="create_project">+ PROJECT</button></a
      >
    </p>
    {% endif %}
  </div>
</main>
{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <h1>Create a new task</h1>
    <form method="post" class="narrow-form">
      {% csrf_token %}{{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
</main>
{% endblock content %}

tasks/templates/tasks/detail.html
{% extends 'base.html' %} {% block content %}
<main>
  <h1>{{ task.name }}</h1>
  <p class="task">{{ task.description }}</p>
</main>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %} {% load static %} 
<header>
    <div>
        <a href="{% url 'recipe_detail' recipe.pk %}">
    </div>
</header>
{% block content %}
<main>
  <div>
    <h1>My Tasks</h1>
    {% if task_list|length == 0 %}
    <p>You have no tasks</p>
    {% else %}
    <table class="task_table">
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for task in task_list %}
        <tr>
          {% if task.is_complete == True %}
          <td>&#10004;</td>
          {% else %}
          <td>
            <form method="post" action="{% url 'complete_task' task.id %}">
              {% csrf_token %}
              <input type="hidden" name="is_completed" value="True" />
              <button class="task_complete">&#10004;</button>
            </form>
          </td>
          {% endif %}     
          <td><a href="{% url 'task_detail' task.id %}">{{ task.name }}</a></td>
          <td>{{ task.start_date }}</td>
          <td>{{ task.due_date }}</td>
               
          <td class="delete_task">
            <form method="post" action="{% url 'delete_task' task.id %}">
            {% csrf_token %}
              <input type="hidden" name="delete_task" value="True" />
              <button class="task_delete">X</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  <div>
    <p>
      <a href="{% url 'create_task' %}"><button class="task_create">+ TASK</button></a>
    </p>
  </div>
</main>
{% endblock content %}